MODEL:
  META_ARCHITECTURE: "PanopticFCN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [1.0, 1.0, 1.0]
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  LOSS_WEIGHT:
    SEGMENT: 3.0
  POSITION_HEAD:
    THING:
      POS_NUM: 3
      NUM_CLASSES: 37
      THRES: 0.2
      TOP_NUM: 200
    STUFF:
      THRES: 0.1
      NUM_CLASSES: 29
      WITH_THING: True  # Check that this is not a problem
      ALL_CLASSES: False
  SEM_SEG_HEAD:
    NUM_CLASSES: 29
  KERNEL_HEAD:
    INSTANCE_SCALES: ((1, 128), (64, 256), (128, 512), (256, 1024), (512, 4096),)
    TEST_SCALES: ((1, 128), (128, 256), (256, 512), (512, 1024), (1024, 4096),)
    DEFORM: False
  TENSOR_DIM: 400  # Adapted because max inst. per img > 100
  INFERENCE:
    INST_THRES: 0.5
    SIMILAR_THRES: 0.95
    COMBINE:
      STUFF_AREA_LIMIT: 2048
  FEATURE_ENCODER:
    DEFORM: False
    CONVS_DIM: 256
DATASETS:
  NAME: "Mapillary"
  TRAIN: ("mapillary_vistas_panoptic_train_separated",)
  TEST: ("mapillary_vistas_panoptic_val_separated",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 16
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 1e-4
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  POLY_LR_POWER: 0.9
  WARMUP_ITERS: 2000
  WARMUP_FACTOR: 0.001
  WARMUP_METHOD: "linear"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 5.0
  IMS_PER_BATCH: 32
  MAX_ITER: 150000
  CHECKPOINT_PERIOD: 50000
INPUT:
  MIN_SIZE_TRAIN: (1024, 1152, 1280, 1408, 1536, 1664, 1792, 1920, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 2048
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  CROP:
    MINIMUM_INST_AREA: 1
    ENABLED: True
    TYPE: "absolute"
    SIZE: (1024, 1024)
  MASK_FORMAT: "bitmask"
VERSION: 2
TEST:
  EVAL_PERIOD: 30000
OUTPUT_DIR: "output/panopticfcn_mapillary_vistas"

APPLY_IBS: False
SAVE_PREDICTIONS: False

SEED: 9